import { useCallback } from 'react';

/**
 * PdfExportButton — Generates:
 * 1. A printable PDF of the full itinerary via window.print()
 * 2. A Google Calendar-compatible .ics file download
 */

function formatICSDate(dateStr, timeStr = '09:00') {
  // dateStr = "2026-09-10", timeStr = "09:00 AM"
  const d = new Date(dateStr);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');

  // Parse time
  let hours = 9;
  let minutes = 0;
  if (timeStr) {
    const match = timeStr.match(/(\d+):(\d+)\s*(AM|PM)?/i);
    if (match) {
      hours = parseInt(match[1]);
      minutes = parseInt(match[2]);
      if (match[3] && match[3].toUpperCase() === 'PM' && hours < 12) hours += 12;
      if (match[3] && match[3].toUpperCase() === 'AM' && hours === 12) hours = 0;
    }
  }
  const h = String(hours).padStart(2, '0');
  const m = String(minutes).padStart(2, '0');
  return `${year}${month}${day}T${h}${m}00`;
}

function generateICS(generatedPlan, travelerName) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//GlobeTrotter//TripPlanner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${generatedPlan.destination?.name || 'My Trip'} — GlobeTrotter`,
    `X-WR-TIMEZONE:Asia/Kolkata`,
  ];

  const tripStartDate = generatedPlan.travelDates?.start || new Date().toISOString().split('T')[0];

  generatedPlan.days.forEach((day) => {
    const dayDate = new Date(tripStartDate);
    dayDate.setDate(dayDate.getDate() + (day.dayNumber - 1));
    const dateStr = dayDate.toISOString().split('T')[0];

    day.activities.forEach((act) => {
      const startTime = act.timeRange ? act.timeRange.split(' - ')[0] : '09:00';
      const endTime = act.timeRange ? act.timeRange.split(' - ')[1] : '11:00';
      const dtStart = formatICSDate(dateStr, startTime);
      const dtEnd = formatICSDate(dateStr, endTime);
      const uid = `gt-${act.id || Math.random().toString(36).substr(2, 9)}@globetrotter`;

      const description = [
        act.description || '',
        act.cost === 0 ? 'Free Entry' : `Entry Fee: ₹${act.cost}`,
        act.transitDetail ? `How to Reach: ${act.transitDetail}` : '',
        act.insiderTip ? `Tip: ${act.insiderTip}` : '',
        '',
        'Generated by GlobeTrotter AI Trip Planner',
      ].filter(Boolean).join('\\n');

      lines.push('BEGIN:VEVENT');
      lines.push(`UID:${uid}`);
      lines.push(`DTSTART:${dtStart}`);
      lines.push(`DTEND:${dtEnd}`);
      lines.push(`SUMMARY:${act.name} (Day ${day.dayNumber})`);
      lines.push(`DESCRIPTION:${description}`);
      lines.push(`CATEGORIES:${act.category || 'Tourism'}`);
      lines.push(`STATUS:CONFIRMED`);
      lines.push('END:VEVENT');
    });
  });

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

function triggerICSDownload(icsContent, fileName) {
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function triggerPrintPDF(generatedPlan) {
  const dest = generatedPlan.destination?.name || 'Trip';
  const DAY_COLORS = ['#1d4ed8', '#059669', '#dc2626', '#d97706', '#7c3aed', '#0891b2', '#be185d'];
  const bookingRef = `GT-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
  const startDate = generatedPlan.travelDates?.start || generatedPlan.startDate || new Date().toISOString().split('T')[0];
  const endDate = generatedPlan.travelDates?.end || generatedPlan.endDate || '';
  const totalCost = (generatedPlan.totalEstimatedCost || generatedPlan.estimatedBudget || 0).toLocaleString();

  const daysHTML = (generatedPlan.days || []).map((day, di) => {
    const color = DAY_COLORS[di % DAY_COLORS.length];
    const actsHTML = (day.activities || []).map((act, actIdx) => `
      <div style="border-left: 3px solid ${color}; padding: 12px 16px; margin: 12px 0; background: #f8fafc; border-radius: 0 10px 10px 0; page-break-inside: avoid; border-top: 1px solid #edf2f7; border-right: 1px solid #edf2f7; border-bottom: 1px solid #edf2f7;">
        <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:6px; margin-bottom:6px;">
          <div style="display:flex; align-items:center; gap:8px;">
            <span style="background:${color}; color:white; font-size:11px; font-weight:800; padding:2px 8px; border-radius:4px;">#${actIdx + 1}</span>
            <strong style="font-size:15px; color:#0f172a;">${act.name}</strong>
          </div>
          <div style="display:flex; gap:6px; font-size:11px;">
            <span style="background:#eff6ff; color:#1d4ed8; font-weight:700; padding:3px 8px; border-radius:6px;">${act.slot || 'Morning'}</span>
            ${act.timeRange ? `<span style="background:#f1f5f9; color:#475569; padding:3px 8px; border-radius:6px;">${act.timeRange}</span>` : ''}
          </div>
        </div>
        <p style="font-size:12px; color:#475569; margin:0 0 8px; line-height:1.5;">${act.description || ''}</p>
        <div style="display:flex; gap:16px; font-size:11px; color:#64748b; flex-wrap:wrap; align-items:center;">
          <span>⭐ ${act.rating || 4.8} ★</span>
          <span>⏳ ~${act.duration || 1.5} hrs</span>
          <span style="color:#059669; font-weight:700;">💵 ${act.cost === 0 ? 'Free Entry' : '₹' + act.cost}</span>
          ${act.openingHours ? `<span>🕒 ${act.openingHours}</span>` : ''}
        </div>
        ${act.insiderTip ? `<p style="font-size:11px; color:#b45309; background:#fffbeb; padding:6px 10px; border-radius:6px; margin:8px 0 0; border:1px solid #fde68a;">💡 <strong>Local Tip:</strong> ${act.insiderTip}</p>` : ''}
        ${act.transitDetail ? `<p style="font-size:11px; color:#1d4ed8; margin:6px 0 0;">🚶 <strong>Directions:</strong> ${act.transitDetail}</p>` : ''}
      </div>
    `).join('');

    return `
      <div style="page-break-before: ${di > 0 ? 'always' : 'auto'}; margin-bottom: 24px;">
        <div style="background: linear-gradient(135deg, ${color}, #0f172a); color: white; padding: 14px 20px; border-radius: 12px; margin-bottom: 16px; display:flex; justify-content:space-between; align-items:center;">
          <div>
            <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 1px; opacity: 0.85;">Day ${day.dayNumber} of ${generatedPlan.totalDays}</div>
            <h2 style="margin: 2px 0 0; font-size: 18px; font-weight: 800;">${day.themeTitle || 'Day ' + day.dayNumber}</h2>
            ${day.themeDescription ? `<p style="margin: 4px 0 0; font-size: 12px; opacity: 0.85;">${day.themeDescription}</p>` : ''}
          </div>
          <div style="text-align:right;">
            <div style="font-size:11px; opacity:0.8;">Est. Day Budget</div>
            <div style="font-size:16px; font-weight:800; color:#4ade80;">₹${(day.estimatedDayCost || 0).toLocaleString()}</div>
          </div>
        </div>
        ${actsHTML}
        ${day.suggestedMeals ? `
          <div style="background: #fefce8; border: 1px solid #fef08a; padding: 10px 16px; border-radius: 8px; margin-top: 12px; font-size: 12px; color: #854d0e;">
            🍽️ <strong>Dining Recommendations:</strong> ${day.suggestedMeals.lunch || ''} • ${day.suggestedMeals.dinner || ''}
          </div>` : ''}
      </div>
    `;
  }).join('');

  const printWindow = window.open('', '_blank', 'width=950,height=750');
  printWindow.document.write(`
    <!DOCTYPE html><html><head>
    <title>GlobeTrotter — ${dest} Boarding Pass & Itinerary Voucher</title>
    <meta charset="UTF-8">
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Plus Jakarta Sans', 'Segoe UI', Arial, sans-serif; color: #0f172a; line-height: 1.5; padding: 24px; max-width: 900px; margin: 0 auto; background: white; }
      @media print { body { padding: 0; } .no-print { display: none; } }
      @page { margin: 12mm; }
    </style>
    </head><body>
    
    <!-- LUXURY BOARDING PASS & TRAVEL VOUCHER -->
    <div style="background: #0f172a; color: white; border-radius: 18px; overflow: hidden; margin-bottom: 28px; box-shadow: 0 10px 30px rgba(0,0,0,0.15); border: 2px solid #1e293b;">
      <div style="padding: 20px 24px; background: linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%); display:flex; justify-content:space-between; align-items:center;">
        <div style="display:flex; align-items:center; gap:10px;">
          <span style="font-size:2rem;">🌍</span>
          <div>
            <h1 style="font-size:22px; font-weight:800; margin:0; letter-spacing:-0.5px;">GlobeTrotter Official Travel Voucher</h1>
            <p style="font-size:11px; opacity:0.85; margin:0;">AI-Generated Smart Itinerary &amp; Boarding Pass</p>
          </div>
        </div>
        <div style="text-align:right;">
          <span style="background: #22c55e; color: #052e16; font-weight:800; font-size:11px; padding:4px 12px; border-radius:9999px; display:inline-block; margin-bottom:4px;">CONFIRMED</span>
          <div style="font-size:12px; font-family:monospace; letter-spacing:1px; color:#bfdbfe;">PNR: ${bookingRef}</div>
        </div>
      </div>

      <div style="display:grid; grid-template-columns: repeat(4, 1fr); gap: 16px; padding: 20px 24px; background: #0f172a; border-bottom: 1px dashed #334155;">
        <div>
          <span style="font-size:10px; text-transform:uppercase; color:#94a3b8; letter-spacing:0.5px;">Destination</span>
          <strong style="display:block; font-size:18px; color:white;">${dest}</strong>
        </div>
        <div>
          <span style="font-size:10px; text-transform:uppercase; color:#94a3b8; letter-spacing:0.5px;">Travel Dates</span>
          <strong style="display:block; font-size:13px; color:white;">${startDate} → ${endDate || 'Return'}</strong>
        </div>
        <div>
          <span style="font-size:10px; text-transform:uppercase; color:#94a3b8; letter-spacing:0.5px;">Duration</span>
          <strong style="display:block; font-size:15px; color:#38bdf8;">${generatedPlan.totalDays} Days / ${Math.max(1, generatedPlan.totalDays - 1)} Nights</strong>
        </div>
        <div>
          <span style="font-size:10px; text-transform:uppercase; color:#94a3b8; letter-spacing:0.5px;">Estimated Budget</span>
          <strong style="display:block; font-size:17px; color:#4ade80;">₹${totalCost}</strong>
        </div>
      </div>

      <div style="padding: 14px 24px; background: #020617; display:flex; justify-content:space-between; align-items:center; font-size:12px; color:#94a3b8;">
        <div>👤 Travel Group: <strong style="color:white;">${generatedPlan.groupType || 'Solo'}</strong> &nbsp;|&nbsp; 🎒 Style: <strong style="color:white;">${generatedPlan.budgetTier || 'Moderate'}</strong> &nbsp;|&nbsp; ⚡ Pace: <strong style="color:white;">${generatedPlan.pace || 'Balanced'}</strong></div>
        <div style="font-family:monospace; letter-spacing:2px; color:#64748b;">|||||| ||| ||||||| |||| ||||||</div>
      </div>
    </div>
    
    <!-- Emergency Helplines Card -->
    <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 14px 20px; border-radius: 12px; margin-bottom: 24px; page-break-inside: avoid;">
      <strong style="color: #c2410c; font-size: 13px; display:block; margin-bottom:8px;">🚨 24x7 Emergency Helplines &amp; Safety Contacts</strong>
      <div style="display: grid; grid-template-columns: repeat(6, 1fr); gap: 8px; font-size: 12px;">
        <span>🚔 Police: <strong>112</strong></span>
        <span>🚑 Ambulance: <strong>108</strong></span>
        <span>🔥 Fire: <strong>101</strong></span>
        <span>👩 Women: <strong>1091</strong></span>
        <span>🏔️ Tourist: <strong>1363</strong></span>
        <span>🏥 Health: <strong>104</strong></span>
      </div>
    </div>
    
    <!-- Day-by-Day Plan -->
    ${daysHTML}
    
    <!-- Verification Footer -->
    <div style="text-align: center; color: #64748b; font-size: 11px; margin-top: 36px; padding-top: 18px; border-top: 1px solid #e2e8f0; page-break-inside: avoid;">
      <div style="margin-bottom:4px; font-weight:700; color:#0f172a;">GlobeTrotter AI Travel Platform • Verified Travel Voucher</div>
      <div>Booking Reference: ${bookingRef} • Generated on ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</div>
      <div style="margin-top:6px; color:#94a3b8;">Carry this document along with valid government photo ID. Have a safe &amp; memorable journey! 🌟</div>
    </div>
    
    <script>window.onload = function() { window.print(); }</script>
    </body></html>
  `);
  printWindow.document.close();
}

function generateWhatsAppText(generatedPlan) {
  const dest = generatedPlan.destination?.name || 'Trip';
  const lines = [
    `🌍 *GlobeTrotter Itinerary — ${dest}*`,
    `📅 ${generatedPlan.travelDates?.start || generatedPlan.startDate || ''} → ${generatedPlan.travelDates?.end || generatedPlan.endDate || ''}`,
    `⏱️ ${generatedPlan.totalDays} Days | 💰 Est. ₹${(generatedPlan.totalEstimatedCost || generatedPlan.estimatedBudget || 0).toLocaleString()}`,
    ''
  ];
  (generatedPlan.days || []).forEach(day => {
    lines.push(`*📅 Day ${day.dayNumber}: ${day.themeTitle || 'Day ' + day.dayNumber}*`);
    (day.activities || []).forEach(act => {
      lines.push(`  • ${act.name} (${act.slot || 'Morning'}) — ${act.cost === 0 ? 'Free' : '₹' + act.cost}`);
      if (act.insiderTip) lines.push(`    💡 Tip: ${act.insiderTip}`);
    });
    if (day.suggestedMeals) {
      lines.push(`  🍽️ Dining: ${day.suggestedMeals.lunch || ''} • ${day.suggestedMeals.dinner || ''}`);
    }
    lines.push('');
  });
  lines.push('Generated by GlobeTrotter AI Trip Planner 🚀');
  lines.push('https://globetrotter.app');
  return lines.join('\n');
}

export default function PdfExportButton({ generatedPlan }) {
  const handlePDF = useCallback(() => {
    if (!generatedPlan) return;
    triggerPrintPDF(generatedPlan);
  }, [generatedPlan]);

  const handleICS = useCallback(() => {
    if (!generatedPlan) return;
    const icsContent = generateICS(generatedPlan);
    const destName = (generatedPlan.destination?.name || 'trip').toLowerCase().replace(/\s+/g, '-');
    triggerICSDownload(icsContent, `globetrotter-${destName}-itinerary.ics`);
  }, [generatedPlan]);

  if (!generatedPlan) return null;

  return (
    <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
      {/* PDF Export */}
      <button
        onClick={handlePDF}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          background: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
          color: 'white',
          border: 'none',
          padding: '9px 18px',
          borderRadius: '9999px',
          fontSize: '0.85rem',
          fontWeight: 700,
          cursor: 'pointer',
          boxShadow: '0 4px 12px rgba(37,99,235,0.35)',
          transition: 'all 0.2s',
        }}
        onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
        onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
        title="Download printable PDF travel guide"
      >
        <span>📄</span>
        <span>Export PDF Guide</span>
      </button>

      {/* Calendar .ics Export */}
      <button
        onClick={handleICS}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          background: 'white',
          color: '#16a34a',
          border: '2px solid #16a34a',
          padding: '9px 18px',
          borderRadius: '9999px',
          fontSize: '0.85rem',
          fontWeight: 700,
          cursor: 'pointer',
          transition: 'all 0.2s',
        }}
        onMouseEnter={(e) => { e.currentTarget.style.background = '#16a34a'; e.currentTarget.style.color = 'white'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.background = 'white'; e.currentTarget.style.color = '#16a34a'; e.currentTarget.style.transform = 'translateY(0)'; }}
        title="Add all activities to Google Calendar / Apple Calendar"
      >
        <span>📅</span>
        <span>Add to Calendar (.ics)</span>
      </button>

      {/* WhatsApp Share */}
      <button
        onClick={() => {
          const text = generateWhatsAppText(generatedPlan);
          const encoded = encodeURIComponent(text);
          // Try native share first (mobile)
          if (navigator.share) {
            navigator.share({ title: `${generatedPlan.destination?.name} Itinerary`, text })
              .catch(() => window.open(`https://wa.me/?text=${encoded}`, '_blank'));
          } else {
            window.open(`https://wa.me/?text=${encoded}`, '_blank');
          }
        }}
        style={{
          display: 'flex', alignItems: 'center', gap: '7px',
          background: 'linear-gradient(135deg, #25d366, #128c7e)',
          color: 'white', border: 'none', padding: '9px 18px',
          borderRadius: '9999px', fontSize: '0.85rem', fontWeight: 700,
          cursor: 'pointer', boxShadow: '0 4px 12px rgba(37,211,102,0.35)',
          transition: 'all 0.2s'
        }}
        onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
        onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
        title="Share itinerary on WhatsApp"
      >
        <span>📲</span><span>Share on WhatsApp</span>
      </button>

      {/* JSON Backup */}
      <button
        onClick={() => {
          const backup = {
            destination: generatedPlan.destination,
            tripName: generatedPlan.tripName,
            startDate: generatedPlan.startDate || generatedPlan.travelDates?.start,
            endDate: generatedPlan.endDate || generatedPlan.travelDates?.end,
            totalDays: generatedPlan.totalDays,
            estimatedBudget: generatedPlan.estimatedBudget || generatedPlan.totalEstimatedCost,
            days: generatedPlan.days,
            generated_at: new Date().toISOString(),
            generated_by: 'GlobeTrotter AI Trip Planner'
          };
          const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `globetrotter-${(generatedPlan.destination?.name || 'trip').toLowerCase().replace(/\s+/g, '-')}-backup.json`;
          document.body.appendChild(a); a.click(); document.body.removeChild(a);
          URL.revokeObjectURL(url);
        }}
        style={{
          display: 'flex', alignItems: 'center', gap: '7px',
          background: 'white', color: '#0f172a',
          border: '2px solid #334155', padding: '9px 18px',
          borderRadius: '9999px', fontSize: '0.85rem', fontWeight: 700,
          cursor: 'pointer', transition: 'all 0.2s'
        }}
        onMouseEnter={(e) => { e.currentTarget.style.background = '#0f172a'; e.currentTarget.style.color = 'white'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.background = 'white'; e.currentTarget.style.color = '#0f172a'; e.currentTarget.style.transform = 'translateY(0)'; }}
        title="Download JSON backup of this plan"
      >
        <span>💾</span><span>JSON Backup</span>
      </button>
    </div>
  );
}
